### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by sopeters** [auth0-samples/auth0-multitenant-website#16]
Hi,

I'm getting

"TypeError: Cannot read property 'map' of undefined"

auth0-multitenant-website/routes/tenant.js:11

Could this be because the PORT isn't included?

var groups = req.user._json[`http://${process.env.ROOT_DOMAIN}/claims/groups`]
should it be
var groups = req.user._json[`http://${process.env.ROOT_DOMAIN}:${process.env.PORT}/claims/groups`]

**Comment by sopeters** [comment]
Cannot read property 'map' of undefined
TypeError: Cannot read property 'map' of undefined
    at buildTenants (/Users/spete/Documents/Sven/Work/Laava/workspace/auth0-multitenant-website/routes/tenant.js:11:17)
    at /Users/spete/Documents/Sven/Work/Laava/workspace/auth0-multitenant-website/routes/tenant.js:25:16
    at Layer.handle [as handle_request] (/Users/spete/Documents/Sven/Work/Laava/workspace/auth0-multitenant-website/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/spete/Documents/Sven/Work/Laava/workspace/auth0-multitenant-website/node_modules/express/lib/router/route.js:137:13)
    at /Users/spete/Documents/Sven/Work/Laava/workspace/auth0-multitenant-website/node_modules/connect-ensure-login/lib/ensureLoggedIn.js:50:5
    at Layer.handle [as handle_request] (/Users/spete/Documents/Sven/Work/Laava/workspace/auth0-multitenant-website/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/spete/Documents/Sven/Work/Laava/workspace/auth0-multitenant-website/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/spete/Documents/Sven/Work/Laava/workspace/auth0-multitenant-website/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/spete/Documents/Sven/Work/Laava/workspace/auth0-multitenant-website/node_modules/express/lib/router/layer.js:95:5)
    at /Users/spete/Documents/Sven/Work/Laava/workspace/auth0-multitenant-website/node_modules/express/lib/router/index.js:281:22

**Comment by sopeters** [comment]
Seems to work if I modify 

routes/user.js
routes/tenant.js
lib/tenant.js

to include ${process.env.PORT} in the URLs.

**Comment by dorazouri** [comment]
> Seems to work if I modify
> 
> routes/user.js
> routes/tenant.js
> lib/tenant.js
> 
> to include ${process.env.PORT} in the URLs.

Had the same error and solved it in the same way.
Wish I had seen this issue thread earlier :P
Thanks @sopeters
